### ISSUE TITLE
Unterstützung Snap-Funktionen für alle Layer in QAD

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#68] opened 2020-08-13 11:18 UTC
Die Erweiterung QAD ist ein geniales Plugin und würde uns in vielen Belangen helfen. Wir wünschen uns, dass QAD die Layer-Funktionen von QGIS unterstützt. So könnten nur die gewünschten Layer fassbar gemacht werden.
![layer](https://user-images.githubusercontent.com/33682937/90128560-5f644c00-dd67-11ea-9494-6b1cfaf476a0.png)

Unsere Fragen:
- Ist dies für euch möglich, dies zu programmieren?
- wenn ja, was würde das kosten?

**Comment by p-stutz** [comment] 2020-08-13 11:35
Präzisierung Marcel Ackermann:
Das Snapping-Tool von QAD soll die Einrastfunktion in QGIS berücksichtigen.
![image](https://user-images.githubusercontent.com/33682937/90129854-b2d79980-dd69-11ea-9301-f382dee3aec3.png)
![image](https://user-images.githubusercontent.com/33682937/90129967-e74b5580-dd69-11ea-9d8e-161532fac7df.png)

**Comment by olivierdalang** [comment] 2020-08-19 10:57
I had a look at the plugin code, it seems very well written, so it should be doable. Will check with Matthias for an estiamate.

We just need to clarify how exactly it would work :

Opt. A : we simply ignore the snapping type of the native QGIS snap settings, and use the snap modes of QAD
Opt. B : we try to convert from QGIS snap modes to QAD snap modes when possible (e.g. QGIS's `vertex` would translate to QAD's `segment start/end`, etc.)

Opt. B may get quite confusing at the end, as the match between QAD's settings and QGIS's settings is not exact. So it wouldn't be too clear for the user what QAD snappings exactly are enabled when he changes it from QGIS settings, and the other way around too (for instance, if you check `Start/End`, but not `Segment start/end` in QAD, would you expect QGIS to snap to vertices or not ?).

It's also worth getting the original author/maintainer's feedback on this idea. We can do it anyways, but it would be much better to have his consent.

**Comment by m-kuhn** [comment] 2020-09-09 17:46
Hallo @p-stutz , @olivierdalang hat das weiterverfolgt und eine entsprechende Änderung für QAD eingegeben.
Wir gehen davon aus, dass das in den nächsten Tagen verfügbar gemacht wird, das hängt jedoch vom Maintainer von QAD ab.

**Comment by olivierdalang** [comment] 2020-09-23 06:58
@p-stutz The feature (as described in Opt. A above) has been added in the latest QAD update (3.0.4). Can you test and see if it works as expected ?

**Comment by p-stutz** [comment] 2020-09-23 10:54
Der Wunsch wurde leider nicht umgesetzt. Wir möchten, dass der QAD Snap auch auf alle anderen Layer anspringt. Momentan snapt er nur auf den aktiven Layer (siehe beiliegendes GIF).
![qad](https://user-images.githubusercontent.com/33682937/94004055-62a61b00-fd9c-11ea-9500-f106f00d825b.gif)

**Comment by olivierdalang** [comment] 2020-09-23 11:35
Sorry I have not been very precise: you need to change snapping to "all layers" in QGIS too for this to work.

It also supports other settings (active layer, or advanced configuration),

It is not possible to have QAD **always** snap to all layers, as if there are too many layers, it would get very slow.

![temp](https://user-images.githubusercontent.com/1894106/94007088-2f19bf80-fda1-11ea-9c38-50d7f7038de4.gif)

**Comment by p-stutz** [comment] 2020-09-23 12:05
Thanks, this is exactly what we need! Unfortunately it doesn't work yet ... We are working with QGIS 3.14.16.
![qad1](https://user-images.githubusercontent.com/33682937/94010098-c2ed8a80-fda5-11ea-8ad1-9dfc330b5343.gif)

**Comment by olivierdalang** [comment] 2020-09-23 12:15
Ok thanks for testing !

I'll try to figure out what is going on and let you know (the release was made by the plugin author, so maybe something happened during the release process).

**Comment by olivierdalang** [comment] 2020-09-24 15:23
I tested with an empty profile and the plugin freshly installed from the plugin manager (3.0.4), on QGIS 3.14.16, and here it does work !! Strange...

Maybe you can try to delete the `qad.ini` file (under `%appdata%\QGIS\QGIS3\profiles\default\python\plugins\QAD`) that may have been created in your QGIS plugin folder, and then restart.

Did snapping work at all on that particular project/layer before the change ?
Does regular snapping work ? (digitizing with QGIS's tools instead of QAD)
Do you maybe have different layer/project CRS ?

If nothing above helps, can you share your QGIS project and the layers so I can try to reproduce the issue to investigate ?

![qad](https://user-images.githubusercontent.com/1894106/94165061-1802cc80-fe8a-11ea-86f9-c065f6c44391.gif)

**Comment by p-stutz** [comment] 2020-09-25 08:10
It seems that the problem is with snapping to PostGIS data. It works with GeoPackage (test verschnitt) data. However, if PostGIS data is exported to GeoPackage, the snapping does not work again (test eo_linie).
![qad2](https://user-images.githubusercontent.com/33682937/94243105-42e73200-ff17-11ea-8cf5-b4d60eeb71a4.gif)

**Comment by olivierdalang** [comment] 2020-09-25 10:43
@p-stutz 
I'm unable to reproduce the issue here. Here it works well with postgis layers, even with different CRS... It's really a surprising issue, as snapping should not be related to the underlying provider.

I'm sorry, I'll have to ask for some more work on your side to be able to fix this, since it's almost impossible to guess what could be going on as long as I'm not able to reproduce the issue...

Can you please :
- send me the data (Geopackage and/or postgres dump and QGIS project) where you have the issue
- test whether regular snapping works (using normal QGIS digitize feature tool), to make sure this is QAD's fault and not some other QGIS bug
- see if anything appears in the QGIS message log, esp. in the "Python error" or "Python warning" tabs (view > panels > log messages) or the QAD message log (view > panels > QAD text window)
- test if you experience the same issue with a empty user profile and a new QGIS layer (to see if the issue isn't linked to some issue with the data or user preferences)

**Comment by p-stutz** [comment] 2020-09-25 11:26
That is very strange. First I'll send you a GeoPackage-File. The layer test is to record lines and the layer eo_linie as reference. The last layer was exported from the PostGIS database. I'm curious if you can reference this. With the QGIS digitize feature tool it works.

The last two points you have written were successfully tested by Marcel Ackermann (no warning or error appeared).

![qad3](https://user-images.githubusercontent.com/33682937/94261709-99ae3500-ff32-11ea-8e30-5d3432e336cc.gif)

[qad.zip](https://github.com/opengisch/QGIS-Issues-SH/files/5282455/qad.zip)

**Comment by olivierdalang** [comment] 2020-10-02 14:03
Ok I think I've understood the issue thanks to your file.

It seems the geometry type of the layer is `MultiCurve`, which it appears is not recognized by QAD. If you convert the geometry type to `MultiLineString`, it should work.

I think this can be considered a bug of the plugin, and since after chasing down the issue, it's an easy fix, I've opened another change request on the QAD plugin directly : https://github.com/gam17/QAD/pull/54
Just like last time, it will depend on the author if and when this will be released to the plugin manager.

By the way, the issue was existing before the last improvements (about snapping layers), so it was a different issue.

**Comment by p-stutz** [comment] 2020-10-05 05:56
It looks like it's what you describe. I believe all types of geometry with arcs have the same problem (CurvePolygon, MultiSurface).

**Comment by olivierdalang** [comment] 2020-11-12 09:45
@p-stutz It seems the plugin author is willing to apply the fix, but he hasn't yet made a release, nor is he sure on when he'll do.

If you need the fix in the mean time, you can manually install the fixed plugin from here : https://github.com/olivierdalang/QAD/archive/fix_curves.zip

**Comment by romefi** [comment] 2022-03-03 08:11
@p-stutz bitte schliessen, falls Problem gelöst

**Closed as completed by romefi** 2022-03-03 08:11 UTC
